name: tweet

on:
  issues: 
  pull_request:
  push:
    branches:
      - notify # for testing purposes

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: get event payload url
        uses: TimothyStiles/EventuallyUrl@v1.1.0
      - name: debug
        uses: hmarr/debug-action@v2
      - name: post event url to twitter
        uses: m1ner79/Github-Twittction@v1.0.1
        with:
            twitter_status: ${{ env.EVENT_URL }}
            twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }} 
            twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }} 
            twitter_access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN }} 
            twitter_access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
